# https://taskfile.dev

version: "3"

env:
  EXT: '{{if eq OS "windows"}}.exe{{else}}{{end}}'
  PROJECT_NAME: gobit

tasks:
  docker:up:
    dir: ./docker
    cmds:
      - docker compose -p $PROJECT_NAME --env-file ../.env up -d
  docker:down:
    dir: ./docker
    cmds:
      - docker compose -p $PROJECT_NAME --env-file ../.env down
  docker:stop:
    dir: ./docker
    cmds:
      - docker compose -p $PROJECT_NAME --env-file ../.env stop
  build:http:
    cmds:
      - go build -v -o ./dist/app ./cmd/http
    sources:
      - ./**/*.go
      - ./.env
  build:http:dev:
    cmds:
      - go build -o ./tmp/main$EXT ./cmd/http
    sources:
      - ./features/**/*.go
      - ./internal/**/*.go
      - ./cmd/**/*.go
      - ./.env
    generates:
      - ./tmp/main$EXT
  migrate:
    cmds:
      - go run ./cmd/migrate
  seed:
    cmds:
      - go run ./cmd/seed
  dev:
    cmds:
      - task: build:http:dev
      - ./tmp/main$EXT
