# https://taskfile.dev

version: "3"

env:
  EXT: '{{if eq OS "windows"}}.exe{{else}}{{end}}'

tasks:
  build:http:
    cmds:
      - go build -v -o ./dist/app ./cmd/http
    sources:
      - ./**/*.go
      - ./.env
  build:http:dev:
    cmds:
      - go build -o ./tmp/main$EXT ./cmd/http
    sources:
      - ./features/**/*.go
      - ./internal/**/*.go
      - ./cmd/**/*.go
      - ./.env
    generates:
      - ./tmp/main$EXT
  migrate:
    cmds:
      - go run ./cmd/migrate
  dev:
    cmds:
      - task: build:http:dev
      - ./tmp/main$EXT
