# https://taskfile.dev

version: "3"

env:
  EXT: '{{if eq OS "windows"}}.exe{{else}}{{end}}'

tasks:
  build:
    cmds:
      - go build -v -o ./dist/app ./cmd/serve
    sources:
      - ./**/*.go
      - ./.env
  build-dev:
    cmds:
      - go build -o ./tmp/main$EXT ./cmd/serve
    sources:
      - ./features/**/*.go
      - ./internal/**/*.go
      - ./cmd/**/*.go
      - ./.env
    generates:
      - ./tmp/main$EXT
  migrate:
    cmds:
      - go run ./cmd/migrate
  dev:
    cmds:
      - task: build-dev
      - ./tmp/main$EXT
