version: "3.7"
services:
  kafka-server:
    image: bitnami/kafka:3.5
    ports:
      - 9094:9094
    expose:
      - 9092
      - 9093
    networks:
      - intranet
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-server:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-server:9092,EXTERNAL://localhost:9094

  # kafka-console:
  #   image: docker.redpanda.com/redpandadata/console:latest
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - intranet
  #   depends_on:
  #     - kafka-server
  #   environment:
  #     KAFKA_BROKERS: kafka-server:9092

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    networks:
      - intranet
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DB}

  redis:
    image: redis:7
    networks:
      - intranet
    ports:
      - 6379:6379

networks:
  intranet:
